### PR TITLE
forge-get-repository: Add missing arg in generic.

### PR DESCRIPTION
**Pull request by cireu**
----

#

### CODE REVIEW

**Comment by tarsius** [comment]
There isn't actually a single method with exactly this signature and only one method takes DEMAND as the first argument. The reason this argument is documented here is that several methods take such an argument *somewhere* and documenting it here means we only have to do it once.

In light of that I don't think it not appropriate to add DEMAND to the signature of the generic function (which by the way only serves as documentation anyway).

**Comment by cireu** [comment]
I see, the arg of `forge-get-repository` have both internal and external usage and each usage have variant meanings, right?

But I still suggest you add an placeholder in arglist of generic to mind people send an arg to call this function.

**Comment by tarsius** [comment]
I'll think about it.

**Comment by tarsius** [comment]
I ended up merging this after all.

**Pull request closed without merging**
