### PR TITLE
fix keybind for pullreq and issue creation

### PR DESCRIPTION
**Pull request by tvraman**
----

#

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks!

**Comment by tvraman** [comment]
My pleasure, and thanks for magit/forge and all your help in my journey
on understanding it.
--

**Comment by tarsius** [comment]
You are welcome!
Feel free to approach we with more questions.
I might not always be as responsive as I was this time around though.

**Comment by tvraman** [comment]
Not a problem re responsiveness, I work on emacs projects in my
spare-time as well and I too dont always respond promptly on those.
--

**Pull request merged**
